site_name: PurrBot Documentation
site_description: 'API-Documentation and Wiki of *Purr*'
site_author: 'Andre_601'

copyright: |
  Docs made with 
  <img alt="❤" class="twemoji md-footer-custom-text" src="https://twemoji.maxcdn.com/v/latest/svg/2764.svg" title="love"> 
  and provided under the 
  <a href="https://github.com/purrbot-site/Docs/blob/master/LICENSE" target="_blank">MIT-License</a>.

docs_dir: docs/

repo_name: Andre601/PurrBot
repo_url: https://github.com/Andre601/PurrBot
edit_uri: https://github.com/purrbot-site/Docs/edit/master/docs

nav:
  - Welcome: index.md
  - API:
    - API: api/index.md
    - PurrBotAPI: api/purrbotapi.md
    - ImageAPI: api/imageapi.md
  - Bot:
    - Wiki: bot/index.md
    - Commands: bot/commands.md
    - Credits: bot/credits.md
    - FAQ: bot/faq.md
    - Selfhosting: bot/selfhosting.md
    - Welcome Channel: bot/welcome-channel.md
    - Welcome Images: bot/welcome-images.md
  - Contributing:
    - Contribute: contribute/index.md
    - Formatting Help: contribute/formatting-help.md

theme:
  name: 'material'
  custom_dir: 'override'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/logo.png'
  palette:
    primary: 'cyan'
    accent: 'blue'
  features:
  - tabs
  icon:
    repo: fontawesome/brands/github-square

extra_css:
  - 'assets/css/extra.css'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/purrbot-site'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/TruePurrBot'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
