site_name: PurrBot API-Documentation
site_description: 'An image-API for everyone.'
site_author: 'Andre_601'

docs_dir: docs/

repo_name: Andre601/PurrBot
repo_url: https://github.com/Andre601/PurrBot
edit_uri: https://github.com/purrbot-site/Docs/edit/master/docs

nav:
  - Welcome: index.md
  - API:
    - API: api/index.md
    - PurrBotAPI: api/purrbotapi.md
    - ImageAPI: api/imageapi.md
  - Bot:
    - Wiki: bot/index.md
    - Commands: bot/commands.md
    - Credits: bot/credits.md
    - FAQ: bot/faq.md
    - Selfhosting: bot/selfhosting.md
    - Welcome Channel: bot/welcome-channel.md
    - Welcome Images: bot/welcome-images.md

theme:
  name: 'material'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/logo.png'
  palette:
    primary: 'cyan'
    accent: 'blue'
  feature:
    tabs: true

extra_css:
  - 'assets/css/dark.css'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/purrbot-site'
    - type: 'twitter'
      link: 'https://twitter.com/TruePurrBot'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
